version: "3.8"

volumes:
  pgdata:

networks:
  dev:
    driver: bridge

services:
  api:
    container_name: api
    env_file:
      - api.env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgdb
    ports:
      - ${API_PORT}:${API_PORT}

  pgdb:
    container_name: pgdb
    env_file:
      - pgdb.env
    image: postgres:15-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
